[package]
name = "bgfx-rs"
version = "0.2.0"
authors = ["Johan Sköld <johan@skold.cc>", "John Benard <linuxydable@linuxydable.fr>"]

[dependencies]
bitflags = "1.2.1"
libc = "0.2.70"

[dependencies.bgfx-sys]
path = "bgfx-sys/"

[dev-dependencies]
cgmath = "0.17.0"
glutin = "0.24.0"
time = "0.2.16"
